spring.application.name=capcatalog

server.port=${PORT:8081}

spring.elasticsearch.uris=${ELASTICSEARCH_URI:http://localhost:9200}
spring.elasticsearch.username=${ELASTICSEARCH_USERNAME:}
spring.elasticsearch.password=${ELASTICSEARCH_PASSWORD:}